export const USERS = {
  status: "OK",
  code: 200,
  total: 10,
  data: [
    {
      id: 1,
      firstname: "Foo",
      lastname: "Nolan",
      email: "roma38@pouros.com",
      phone: "+4021075854684",
      birthday: "2016-03-25",
      gender: "male",
      address: {
        id: 0,
        street: "Street",
        streetName: "Street name",
        buildingNumber: "30441",
        city: "City",
        zipcode: "ZIP",
        country: "Country",
        county_code: "NA",
        latitude: -68.004835,
        longitude: -152.173777,
      },
      website: "http://stark.org",
      image: "http://placeimg.com/640/480/people",
    },
    {
      id: 2,
      firstname: "Foo",
      lastname: "Fadel",
      email: "jenkins.nelle@hotmail.com",
      phone: "+6319970533953",
      birthday: "2009-10-01",
      gender: "male",
      address: {
        id: 0,
        street: "1726 Pfeffer Vista",
        streetName: "Kilback Cliff",
        buildingNumber: "506",
        city: "West Idaview",
        zipcode: "98801",
        country: "Trinidad and Tobago",
        county_code: "TH",
        latitude: -71.663989,
        longitude: 68.157722,
      },
      website: "http://emard.net",
      image: "http://placeimg.com/640/480/people",
    },
    {
      id: 3,
      firstname: "Foo",
      lastname: "Mraz",
      email: "webster.maggio@yahoo.com",
      phone: "+5785502526973",
      birthday: "2014-11-30",
      gender: "male",
      address: {
        id: 0,
        street: "69583 Cathrine Inlet Apt. 296",
        streetName: "Schuppe Crescent",
        buildingNumber: "3409",
        city: "South Barton",
        zipcode: "38233-3003",
        country: "Italy",
        county_code: "AZ",
        latitude: 81.486863,
        longitude: -143.83485,
      },
      website: "http://emmerich.biz",
      image: "http://placeimg.com/640/480/people",
    },
    {
      id: 4,
      firstname: "Foo",
      lastname: "Daugherty",
      email: "melvina.maggio@crist.com",
      phone: "+4919051877619",
      birthday: "2012-07-02",
      gender: "male",
      address: {
        id: 0,
        street: "3502 Stephanie Viaduct Suite 733",
        streetName: "Veum Estates",
        buildingNumber: "62650",
        city: "Hillardmouth",
        zipcode: "88796-4244",
        country: "Cambodia",
        county_code: "HN",
        latitude: 74.782466,
        longitude: -178.780078,
      },
      website: "http://tremblay.com",
      image: "http://placeimg.com/640/480/people",
    },
    {
      id: 5,
      firstname: "Foo",
      lastname: "Barton",
      email: "eric74@gmail.com",
      phone: "+4818799877944",
      birthday: "2019-06-15",
      gender: "male",
      address: {
        id: 0,
        street: "616 Robel Springs",
        streetName: "Wintheiser Key",
        buildingNumber: "940",
        city: "Olsonborough",
        zipcode: "39004-4911",
        country: "Israel",
        county_code: "KM",
        latitude: 0.753324,
        longitude: 135.101061,
      },
      website: "http://larson.info",
      image: "http://placeimg.com/640/480/people",
    },
    {
      id: 6,
      firstname: "Foo",
      lastname: "Stanton",
      email: "kraig59@connelly.com",
      phone: "+2907318403556",
      birthday: "2018-01-14",
      gender: "male",
      address: {
        id: 0,
        street: "17102 Corwin Highway Suite 842",
        streetName: "Williamson Turnpike",
        buildingNumber: "4066",
        city: "North Kobe",
        zipcode: "80911",
        country: "Chile",
        county_code: "KW",
        latitude: 75.113599,
        longitude: 164.762103,
      },
      website: "http://emmerich.com",
      image: "http://placeimg.com/640/480/people",
    },
    {
      id: 7,
      firstname: "Foo",
      lastname: "Kiehn",
      email: "arnoldo.conroy@kshlerin.com",
      phone: "+7192448059642",
      birthday: "2007-06-25",
      gender: "male",
      address: {
        id: 0,
        street: "828 Jorge Shore Suite 042",
        streetName: "Elyse Brooks",
        buildingNumber: "1310",
        city: "East Antonioshire",
        zipcode: "91289",
        country: "Brunei Darussalam",
        county_code: "AT",
        latitude: -16.723646,
        longitude: 89.420063,
      },
      website: "http://dubuque.biz",
      image: "http://placeimg.com/640/480/people",
    },
    {
      id: 8,
      firstname: "Foo",
      lastname: "Kertzmann",
      email: "uvandervort@kautzer.com",
      phone: "+3210364087447",
      birthday: "2008-08-15",
      gender: "male",
      address: {
        id: 0,
        street: "98123 Hermann Ford",
        streetName: "Harmon Ridges",
        buildingNumber: "30741",
        city: "Croninville",
        zipcode: "50280",
        country: "Latvia",
        county_code: "DK",
        latitude: 53.742622,
        longitude: -95.431399,
      },
      website: "http://hermiston.com",
      image: "http://placeimg.com/640/480/people",
    },
    {
      id: 9,
      firstname: "Foo",
      lastname: "Kessler",
      email: "robert62@king.biz",
      phone: "+2572593024491",
      birthday: "2016-05-02",
      gender: "male",
      address: {
        id: 0,
        street: "230 Roman Path Apt. 202",
        streetName: "Shields Lakes",
        buildingNumber: "22657",
        city: "Jazmyneton",
        zipcode: "28364",
        country: "Macedonia",
        county_code: "NL",
        latitude: 24.974711,
        longitude: 47.976446,
      },
      website: "http://littel.com",
      image: "http://placeimg.com/640/480/people",
    },
    {
      id: 10,
      firstname: "Foo",
      lastname: "Bode",
      email: "pollich.bella@ohara.com",
      phone: "+5315210644513",
      birthday: "2018-05-11",
      gender: "male",
      address: {
        id: 0,
        street: "11126 Considine Rapids Suite 419",
        streetName: "Rohan Ports",
        buildingNumber: "6514",
        city: "South Anastasia",
        zipcode: "24117",
        country: "Saint Vincent and the Grenadines",
        county_code: "NR",
        latitude: 3.246659,
        longitude: -140.822294,
      },
      website: "http://witting.com",
      image: "http://placeimg.com/640/480/people",
    },
  ],
};
